### ISSUE TITLE
Hoster der Webseite bekannt geben

### ISSUE THREAD

**Issue by mritzmann** [dnszensur/dnszensur-web#42]
https://twitter.com/schulerswiss/status/921713204241272833

> Cooles Endergebnis 👍. Wer den Content hostet wär noch interessant in der Liste 😀.

**Comment by MarcelWaldvogel** [comment]
Ist jetzt drin, danke. Aber bisher nur von Hosts, die bei der Swisscom geblockt werden. Wird sich das noch ändern?

**Comment by mritzmann** [comment]
Das Feature wurde gestern Abend eingebaut. Die Aktualisierung der Swisscom DB wurde daraufhin von Hand angestossen. UPC folgt.

Ich schliesse dieses Issue Mal da doppelt vorhanden: https://github.com/dnszensur/dnszensur-crawler/issues/4

**Comment by mritzmann** [comment]
@MarcelWaldvogel UPC ist nun ebenfalls aktualisiert. (Falls noch nichts angezeigt wirdt: Die Webseite cached sehr stark)
