### ISSUE TITLE
ip-api.com liefert falsche Werte falls Hoster nicht ermittelt werden konnte

### ISSUE THREAD

**Issue by mritzmann** [dnszensur/dnszensur-web#47]
_Issue am 04.11.2017 abgeschlossen und aus transparenzgründen mit allen notwendigen Informationen ergänzt_

---

## Zusammenfassung

Seit ein par Tagen kann auf [DNSzensur.ch](https://dnszensur.ch/) eingesehen werden, bei welchen Hostern und in welchen Ländern die gesperrten Webseiten gehostet werden.

Auszug [FAQ](https://dnszensur.ch/faq.php):

> Wie wird der Serverstandort und der Hoster ermittelt?
> 
> Hierzu nutzen wir die API von ip-api.com. Abgefragt wird nur die eigentliche Domain ohne Subdomains. Es ist möglich, dass die Subdomain www (oder eine beliebig andere) auf einen anderen Server zeigt.

Eine Abfrage mit der [ip-api.com](http://ip-api.com/) API sieht wie folgt aus:

```sh
markus@kari ~> curl "http://ip-api.com/json/example.com?fields=country,as"
{"as":"AS15133 MCI Communications Services, Inc. d/b/a Verizon Business","country":"United States"}
```

Nun hat sich herausgestellt, dass die API immer den Wert `as:AS197540 netcup GmbH` ausgibt, falls der Hoster nicht ermittelt werden konnte. Hierbei handelt es sich offensichtlich um einen Bug der API.

Beispiel:

```sh
markus@kari ~> curl "http://ip-api.com/json/domain-gibt-es-nicht.com?fields=country,as"
{"as":"AS197540 netcup GmbH","country":"Germany"}

markus@kari ~> curl "http://ip-api.com/json/subdoman-gibt-es-nicht.dnszensur.ch?fields=country,as"
{"as":"AS197540 netcup GmbH","country":"Germany"}
```

Als kurzfristige Maßnahme wurden alle Werte mit `AS197540 netcup GmbH` aus der Datenbank gelöscht. Zudem wurde der Entwickler der API angeschrieben und auf den Fehler aufmerksam gemacht.

## Chronik

- **03.11.2017 17:29:** Felix Preuß von netcup GmbH macht per E-Mail auf den Fehler aufmerksam.
- **03.11.2017 23:56:** Problem angeschaut, Fehler nachvollziehbar.
- **04.11.2017 01:15:** Vorübergehend alle Werte mit `AS197540 netcup GmbH` [aus der Datenbank gelöscht](https://gist.github.com/mritzmann/522fc0b2dd2dbe25d06ffeb4b397b50a). JSON-Files neu generiert und CDN-Cache gelöscht.

---

```
Guten Tag Herr Ritzmann,

vielen Dank!

Bitte geben Sie mir kurz eine Rückmeldung, wenn unser Name aus den Listen verschwunden ist.

Mit freundlichen Grüßen

Felix Preuß
Managing Director netcup GmbH

---------------------------------------------------------
netcup GmbH
Daimlerstraße 25
D-76185 Karlsruhe

Telefon: +49 721 / 7540755 - 0
Telefax: +49 721 / 7540755 - 9

Kunden- und Interessenten-Hotline: 08000 netcup
(Kostenlos aus dem Festnetz der Deutschen Telekom)

Web: www.netcup.de
eMail: mail@netcup.de

Handelsregister: HRB 705547, Amtsgericht Mannheim

Geschäftsführer:
- Dipl.-Ing. (BA) Felix Preuß
- Dipl.-Ing. (BA) Oliver Werner

USt.-IdNr.: DE262851304
--------------------------------------------------------- 

03.11.2017 17:34 - markus@dnszensur.ch schrieb:

> Guten Abend Herr Preuß
>
> Das war selbstverständlich nicht beabsichtigt. Ich schaue mir das
> spätestens morgen an. Vielen Dank für ihre Information.
>
> Freundliche Grüsse
> Markus Ritzmann
>
> On 03.11.2017 17:29, netcup Team wrote:
>> Guten Tag Herr Ritzmann,
>>
>>
>> Ihre Seite dnszensur.ch nutzt für DNS-Abfragen ip-api.com . Ich musste feststellen, dass ip-api.com immer auf die IP 46.38.243.234 auflöst, wenn eine Zone nicht existent ist. Aufgrund dieses Fehlers sind wir als Provider bei Ihnen gelistet, der die meisten illegalen Websites hostet. Das führt zu negativer PR und einigen Supportanfragen bei uns. So etwas ist ärgerlich für uns.
>>
>> Ich bitte Sie den Fehler zeitnah zu beheben und um eine Richtigstellung, dass die aufgelisteten Domains niemals bei uns gehostet waren.
>>
>> Vielen Dank!
>>
>> Ansonsten wünsche ich Ihnen weiterhin viel Erfolg beim Betrieb von dnszensur.ch . Eine solche Website ist sicherlich wichtig für die Transparenz, die im Internet geboten werden sollte.
>>
>>
>> Mit freundlichen Grüßen
>>
>> Felix Preuß
>> Managing Director netcup GmbH
>>
>> ---------------------------------------------------------
>> netcup GmbH
>> Daimlerstraße 25
>> D-76185 Karlsruhe
>>
>> Telefon: +49 721 / 7540755 - 0
>> Telefax: +49 721 / 7540755 - 9
>>
>> Kunden- und Interessenten-Hotline: 08000 netcup
>> (Kostenlos aus dem Festnetz der Deutschen Telekom)
>>
>> Web: www.netcup.de
>> eMail: mail@netcup.de
>>
>> Handelsregister: HRB 705547, Amtsgericht Mannheim
>>
>> Geschäftsführer:
>> - Dipl.-Ing. (BA) Felix Preuß
>> - Dipl.-Ing. (BA) Oliver Werner
>>
>> USt.-IdNr.: DE262851304
>> --------------------------------------------------------- 
>>
>
> -- 
> Twitter: @RitzmannMarkus
> Web: https://markusritzmann.ch
```

**Comment by heubergen** [comment]
Do you need a urgent fix through Europe night? If i still have push permissions I can do something to prevent future damage for the company.

**Comment by mritzmann** [comment]
This ned a fix in dnszensur/dnszensur-crawler, a new crawler run and a rebuild of all json files. This requires DB access. I'll check this out tomorrow.

**Comment by heubergen** [comment]
Not necessarily, there are other fixes possible directly in the php file that the user request. Would just be a urgent fix. 

-- 
Patrick Albrecht 




> 
> 
> 
>

**Comment by mritzmann** [comment]
ip-api.com:

```
Thank you for reporting this. Looks like netcup (the provider) was pushing domain, search via DHCP to our servers:

# cat /etc/resolv.conf
domain ultrasrv.de
search ultrasrv.de
```
